### ISSUE TITLE
Bug in read-line

### ISSUE THREAD

**Issue by Arjuna144** [LuxLang/lux-stdlib#1]
I hope this is not my fault again, but it seems as if there is a bug in read-line.
It always goes into the first case because something with the close is not working:
```
             (case [output _close]
               (\or [(#;Left _) _] [_ (#;Left _)]) #;None
               [(#;Right input) (#;Right _)]       (#;Some input))))))]
```

Here is my output, that shows the returned value of _close:
```
$ java -jar target/jvm/program.jar          
this should be red and then echoed back!

 Error: 
output:
Right "this should be red and then echoed back!"
_close:
Left "java.lang.IllegalStateException: Can't create variant for null pointer
lux.LuxUtils.sum_make(Unknown Source)
test-lux.myReadLine_-121997577$0.impl(test-lux:38)
test-lux.myReadLine_-121997577$0.apply(test-lux)
lux.codata.io.IO_SLASH_Functor_2136622028$0$0$0.impl(lux/codata/io)
lux.codata.io.IO_SLASH_Functor_2136622028$0$0$0.apply(lux/codata/io)
lux.codata.io.IO_SLASH_Monad_-2065510546$1.impl(lux/codata/io:37)
lux.codata.io.IO_SLASH_Monad_-2065510546$1.apply(lux/codata/io)
lux.control.monad.bind_-1761281656$0$0$0.impl(lux/control/monad:80)
lux.control.monad.bind_-1761281656$0$0$0.apply(lux/control/monad)
test-lux._.main(test-lux.lux:42)"
```

**Comment by LuxLang** [comment]
Hehe.

What do you know! You have found a bug!
Thanks for that. I hadn't thought to check those functions.

You're clearly using v0.3.2.

I just checked. The bug has to do with what happens when you call a method that has a void return.
It's interacting with what happens when you create a variant (you can't have variants with null values, for performance reasons...).

It's a quick fix for me.
I forgot to change what void methods return so they actually return "unit" rather than null.

Thanks for spotting that!

**Comment by LuxLang** [comment]
Fixed in master branch.
Due for v0.3.3.
